// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDwTDQDG2tbWIhXkOwJsicmOBUdqNwboY',
    appId: '1:122063994231:web:cfb9ae8b906313cb2ff572',
    messagingSenderId: '122063994231',
    projectId: 'ecgapp-86a0a',
    authDomain: 'ecgapp-86a0a.firebaseapp.com',
    storageBucket: 'ecgapp-86a0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtdNKkbyRF0O1gpK87vEpRtNq4FzE3kOY',
    appId: '1:122063994231:android:9f8f8ac299cc0e302ff572',
    messagingSenderId: '122063994231',
    projectId: 'ecgapp-86a0a',
    storageBucket: 'ecgapp-86a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuPpgxgNOyY3d3ZmPktBdDNJJbo08bkrw',
    appId: '1:122063994231:ios:4bb9a9b2aec464ba2ff572',
    messagingSenderId: '122063994231',
    projectId: 'ecgapp-86a0a',
    storageBucket: 'ecgapp-86a0a.firebasestorage.app',
    iosBundleId: 'com.example.ecg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuPpgxgNOyY3d3ZmPktBdDNJJbo08bkrw',
    appId: '1:122063994231:ios:4bb9a9b2aec464ba2ff572',
    messagingSenderId: '122063994231',
    projectId: 'ecgapp-86a0a',
    storageBucket: 'ecgapp-86a0a.firebasestorage.app',
    iosBundleId: 'com.example.ecg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDwTDQDG2tbWIhXkOwJsicmOBUdqNwboY',
    appId: '1:122063994231:web:4d337c6a420aee122ff572',
    messagingSenderId: '122063994231',
    projectId: 'ecgapp-86a0a',
    authDomain: 'ecgapp-86a0a.firebaseapp.com',
    storageBucket: 'ecgapp-86a0a.firebasestorage.app',
  );
}
